# Yaml script for Travis-CI

language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - os: linux
      python: 2.7
      env:
      - OPTIONAL_DEPS=1
      - BUILD_DOCS=1
    - os: linux
      python: 2.7
      env:
      - OPTIONAL_DEPS=1
    - os: linux
      python: 2.7
      env:
      - OPTIONAL_DEPS=1
      - PIP_FLAGS="--pre"
    - python: 2.7
    - os: linux
      python: 3.5
      env:
      - OPTIONAL_DEPS=1
      - BUILD_DOCS=1
    - os: linux
      python: 3.5
      env:
      - OPTIONAL_DEPS=1
    - os: linux
      python: 3.5
      env:
      - OPTIONAL_DEPS=1
      - PIP_FLAGS="--pre"
    - python: 3.5
    - os: linux
      python: 3.6
      env:
      - OPTIONAL_DEPS=1
      - BUILD_DOCS=1
    - os: linux
      python: 3.6
      env:
      - OPTIONAL_DEPS=1
    - os: linux
      python: 3.6
      env:
      - OPTIONAL_DEPS=1
      - PIP_FLAGS="--pre"
    - python: 3.6
    - os: linux
      python: 3.7
      env:
      - OPTIONAL_DEPS=1
      - BUILD_DOCS=1
    - os: linux
      python: 3.7
      env:
      - OPTIONAL_DEPS=1
    - os: linux
      python: 3.7
      env:
      - OPTIONAL_DEPS=1
      - PIP_FLAGS="--pre"
    - python: 3.7
    - os: linux
      python: 3.8
      env:
      - OPTIONAL_DEPS=1
      - BUILD_DOCS=1
    - os: linux
      python: 3.8
      env:
      - OPTIONAL_DEPS=1
    - os: linux
      python: 3.8
      env:
      - OPTIONAL_DEPS=1
      - PIP_FLAGS="--pre"
    - python: 3.8
    - os: linux
      python: 3.9
      env:
      - OPTIONAL_DEPS=1
      - BUILD_DOCS=1
    - os: linux
      python: 3.9
      env:
      - OPTIONAL_DEPS=1
    - os: linux
      python: 3.9
      env:
      - OPTIONAL_DEPS=1
      - PIP_FLAGS="--pre"
    - python: 3.9
    - os: linux
      python: 3.10
      env:
      - OPTIONAL_DEPS=1
      - BUILD_DOCS=1
    - os: linux
      python: 3.10
      env:
      - OPTIONAL_DEPS=1
    - os: linux
      python: 3.10
      env:
      - OPTIONAL_DEPS=1
      - PIP_FLAGS="--pre"
    - python: 3.10

install:
  # install required packages
  - pip install --upgrade pip
  # install adg
  - printenv PWD
  # with dev dependencies
  - if [[ "${OPTIONAL_DEPS}" == 1 ]]; then
      pip install --retries 3 ${PIP_FLAGS} -e .[develop];
    fi
  # standard user dependencies
  - if [[ "${OPTIONAL_DEPS}" != 1 ]]; then
      pip install --retries 3 ${PIP_FLAGS} .;
    fi
  # show what's installed
  - python --version
  - pip list

script:
  - if [[ "${BUILD_DOCS}" == 1 ]]; then
      cd doc;
      make html;
      cd ..;
    fi
  - if [[ "${OPTIONAL_DEPS}" == 1 ]]; then
      cd adg/tests;
      source run_test_suite.sh;
      cd ../..;
    fi
